// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqsdqsnmbvwucbmwobct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxc2Rxc25tYnZ3dWNibXdvYmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQ5MDUsImV4cCI6MjA2Mzc3MDkwNX0.dbbSB6fTavSpDMBNLTb3kk3-q8jgdSvy1sQDGiOkZlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);